### ISSUE TITLE
 `sad` npm package name

### ISSUE THREAD

**Issue by phated** [ideaq/halp#3]
I noticed that this module was originally named and published to npm as `sad` but has since changed names.  I was working on a hapi plugin and the name I had in mind was `sad`, so I was wondering if you could unpublish the old version of this module.

Thanks,
-Blaine

**Comment by nelsonic** [comment]
@phated I _temporarily_ re-directed the [**sad**](https://www.npmjs.com/package/sad) module here while I was setting up: https://github.com/pandajs/sad 

What plugin are you working on...?

**Comment by phated** [comment]
Thanks for the response.

**Comment by nelsonic** [comment]
But seriously, if you have a better use for the **sad** namespace, please share, I wold love to collaborate! :+1:

**Comment by phated** [comment]
Thanks.  I've renamed the project to `boomstick` - https://github.com/iceddev/boomstick
